name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: carey036/android_kernel_xiaomi_sdm710
        
    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3
        path: zipper
    - name: Android kernel build
      uses: carey036/android-kernel-actions@master
      id: build
      env:
        NAME: Xs
      with:
        arch: arm64
        compiler: gcc/10
        defconfig: grus_defconfig
        image: Image.gz-dtb
    - name: test
      run: |
          ls
          cd /github/workspace
          ls
          cd /github/workspace/zipper/
          ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: ${{ steps.build.outputs.outfile }}
